package com.agh.hydra.common.model;

public enum FunctionalPrivilege {
    FN_PRV_EDIT_PRIVILEGES,
    FN_PRV_EDIT_COMPANIES,
    FN_PRV_INVALIDATE_COMPANIES,
    FN_PRV_CREATE_INFORMATION,
    FN_PRV_INVALIDATE_RECRUITMENT_INFO,
    FN_PRV_EDIT_JOBS,
    FN_PRV_INVALIDATE_JOBS,
    FN_PRV_CREATE_REFERRAL,
    FN_PRV_INVALIDATE_REFERRAL
}
